# Treinamento de testes, respostas somente de exemplo.
general_training = [
    "Saber data final do periodo",
    "Para saber a data final do periodo acesse o sistema SUAP",
    "telefone do protocolo ou email",
    "Para saber o telefone do protocolo acesse o sistema SUAP",
    "como solicitar declaração",
    "Para solicitar uma declaração acesse o sistema SUAP",
    "como solicitar segunda chamada",
    "Para solicitar segunda chamada acesse o sistema SUAP",
    "como cursar disciplinas pendentes",
    "Para se matriular em disciplinas pendentes acesse o sistema SUAP",
    "trancar curso",
    "Para trancar o curso acesse o sistema SUAP",
    "consultar informações sobre bolsas",
    "Para consultar informações sobre bolsas acesse o sistema SUAP",
    "Atividades extra curriculares.",
    "Para saber mais sobre atividades extra curriculares acesse o sistema SUAP",
    "Solicitar atendimento no setor de saude",
    "Para solicitar atendimento com o setor de saude acesse o sistema SUAP",
    "Informações sobre setor de saude",
    "Para informações sobre o setor de saude acesse o sistema SUAP",
    "Informações sobre estágios",
    "Para informações sobre estágios acesse o sistema SUAP",
    "comprovante de renovação de matricula",
    "Para solicitar comprovante de renovação de matricula acesse o sistema SUAP",
]