# Treinamento de testes, respostas somente de exemplo.
conversation = [
    "Saber data final do periodo",
    "Para saber a data final do periodo acesse o sistema SUAP",
    "telefone do protocolo ou email",
    "Para saber o telefone do protocolo acesse o sistema SUAP",
    "como solicitar declaração",
    "Para solicitar uma declaração acesse o sistema SUAP",
    "como solicitar segunda chamada",
    "Para solicitar segunda chamada acesse o sistema SUAP",
    "como cursar disciplinas pendentes",
    "Para se matriular em disciplinas pendentes acesse o sistema SUAP",
    "trancar curso",
    "Para trancar o curso acesse o sistema SUAP",
    "consultar informações sobre bolsas",
    "Para consultar informações sobre bolsas acesse o sistema SUAP",
    "Atividades extra curriculares.",
    "Para saber mais sobre atividades extra curriculares acesse o sistema SUAP",
    "Solicitar atendimento no setor de saude",
    "Para solicitar atendimento com o setor de saude acesse o sistema SUAP",
    "Informações sobre setor de saude",
    "Para informações sobre o setor de saude acesse o sistema SUAP",
    "Informações sobre estágios",
    "Para informações sobre estágios acesse o sistema SUAP",
    "comprovante de renovação de matricula",
    "Para solicitar comprovante de renovação de matricula acesse o sistema SUAP",
]

teste = [
    'Como está o tempo hoje?',
    'O tempo hoje está nublado, com possibilidade de chuva à tarde.',
    'Qual é a previsão do tempo?',
    'O tempo hoje está nublado, com possibilidade de chuva à tarde.',
    'Está chovendo ou fazendo sol?',
    'O tempo hoje está nublado, com possibilidade de chuva à tarde.',
    'Qual é a temperatura agora?',
    'A temperatura agora é de 25 graus Celsius, com sensação térmica de 27.',
    'Está frio ou calor?',
    'A temperatura agora é de 25 graus Celsius, com sensação térmica de 27.',
    'Quanto graus está fazendo?',
    'A temperatura agora é de 25 graus Celsius, com sensação térmica de 27.'
]
